global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'nbascoring-metrics'
    metrics_path: '/q/metrics'
    scrape_interval: 1s
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: nbascoring-quarkus
  - job_name: 'prometheus'
    static_configs:
      - targets: [ '192.168.15.168:9090' ]